export const AgentAttributes = {
  ID: 'gen_ai.agent.id',
  NAME: 'gen_ai.agent.name',
  ROLE: 'gen_ai.agent.role',
  TEAM: 'gen_ai.agent.team',
  FRAMEWORK: 'gen_ai.agent.framework',
  GOAL: 'gen_ai.agent.goal',
  TASK: 'gen_ai.agent.task',
  TASK_DESCRIPTION: 'gen_ai.agent.task.description',
  CONFIDENCE: 'gen_ai.agent.confidence',
  STATUS: 'gen_ai.agent.status',
  ITERATION: 'gen_ai.agent.iteration',
  DELEGATION_TARGET: 'gen_ai.agent.delegation.target',
  DELEGATION_REASON: 'gen_ai.agent.delegation.reason',
  CRITIQUE_TARGET: 'gen_ai.agent.critique.target',
  CRITIQUE_RESULT: 'gen_ai.agent.critique.result',
  REVIEW_TARGET: 'gen_ai.agent.review.target',
  REVIEW_RESULT: 'gen_ai.agent.review.result',
  HANDOFF_TARGET: 'gen_ai.agent.handoff.target',
  HANDOFF_REASON: 'gen_ai.agent.handoff.reason',
  ESCALATION_TARGET: 'gen_ai.agent.escalation.target',
  ESCALATION_REASON: 'gen_ai.agent.escalation.reason',
  MEMORY_KEY: 'gen_ai.agent.memory.key',
  MEMORY_VALUE: 'gen_ai.agent.memory.value',
  MEMORY_OPERATION: 'gen_ai.agent.memory.operation',
  TOOL_NAME: 'gen_ai.tool.name',
  TOOL_INPUT: 'gen_ai.tool.input',
  TOOL_OUTPUT: 'gen_ai.tool.output',
  TOOL_STATUS: 'gen_ai.tool.status',
  INTERRUPT_ID: 'gen_ai.agent.interrupt.id',
  INTERRUPT_REASON: 'gen_ai.agent.interrupt.reason',
  INTERRUPT_RESUME_URL: 'gen_ai.agent.interrupt.resume_url',
  RESUME_TOKEN: 'gen_ai.agent.resume.token',
  HUMAN_DECISION: 'gen_ai.agent.human.decision',
  HUMAN_INPUT: 'gen_ai.agent.human.input',
  TIMEOUT_AT: 'gen_ai.agent.timeout_at',
  POLICY_REQUIRED_REVIEW: 'gen_ai.agent.policy.required_review',
} as const;

export const MissionAttributes = {
  ID: 'gen_ai.workflow.id',
  BRANCH_ID: 'gen_ai.workflow.branch_id',
  OBJECTIVE: 'gen_ai.workflow.name',
  PHASE: 'gen_ai.workflow.phase',
  STATUS: 'gen_ai.workflow.status',
  OWNER: 'gen_ai.workflow.owner',
  TEAM_SIZE: 'gen_ai.workflow.team_size',
  ENCRYPTION_ENABLED: 'gen_ai.workflow.encryption.enabled',
  FRAMEWORK: 'gen_ai.workflow.framework',
  VERSION: 'gen_ai.workflow.version',
} as const;

export const AgentEvents = {
  DELEGATION: 'agent.delegation',
  DELEGATION_ACCEPTED: 'agent.delegation.accepted',
  DELEGATION_REJECTED: 'agent.delegation.rejected',
  HANDOFF: 'agent.handoff',
  HANDOFF_REQUESTED: 'agent.handoff.requested',
  HANDOFF_ACCEPTED: 'agent.handoff.accepted',
  HANDOFF_REJECTED: 'agent.handoff.rejected',
  CRITIQUE: 'agent.critique',
  REVIEW: 'agent.review',
  REVIEW_APPROVED: 'agent.review.approved',
  REVIEW_CHANGES_REQUESTED: 'agent.review.changes_requested',
  REVIEW_REJECTED: 'agent.review.rejected',
  REFLECTION: 'agent.reflection',
  PLANNING: 'agent.planning',
  DECISION: 'agent.decision',
  RETRY: 'agent.retry',
  ESCALATION: 'agent.escalation',
  APPROVAL: 'agent.approval',
  TIMEOUT: 'agent.timeout',
  MEMORY_READ: 'agent.memory.read',
  MEMORY_WRITE: 'agent.memory.write',
  MEMORY_DELETE: 'agent.memory.delete',
  TOOL_CALL: 'agent.tool.call',
  TOOL_RESULT: 'agent.tool.result',
  TOOL_ERROR: 'agent.tool.error',
  ARTIFACT_CREATED: 'agent.artifact.created',
  ARTIFACT_UPDATED: 'agent.artifact.updated',
  INTERRUPT_REQUESTED: 'agent.interrupt.requested',
  INTERRUPT_RESUMED: 'agent.interrupt.resumed',
  HUMAN_DECISION: 'agent.human.decision',
  MISSION_STARTED: 'mission.started',
  MISSION_PHASE_CHANGED: 'mission.phase.changed',
  MISSION_COMPLETED: 'mission.completed',
  MISSION_FAILED: 'mission.failed',
  LLM_CALL: 'gen_ai.call',
  LLM_RESPONSE: 'gen_ai.response',
  LLM_ERROR: 'gen_ai.error',
  LLM_STREAMING_START: 'gen_ai.streaming.start',
  LLM_STREAMING_END: 'gen_ai.streaming.end',
} as const;

export const AgentSpanKind = {
  MISSION: 'mission',
  ORCHESTRATION: 'agent.orchestration',
  AGENT_TASK: 'invoke_agent',
  TASK: 'invoke_agent',
  DELEGATION: 'agent.delegation',
  TOOL_CALL: 'execute_tool',
  REVIEW: 'agent.review',
  REFLECTION: 'agent.reflection',
  PLANNING: 'agent.planning',
  MEMORY_OP: 'agent.memory.op',
  MEMORY: 'agent.memory.op',
  HUMAN_INPUT: 'agent.human.input',
} as const;

export const Frameworks = {
  CUSTOM: 'custom',
  LANGGRAPH: 'langgraph',
  AUTOGEN: 'autogen',
  CREWAI: 'crewai',
  OPENAI_AGENTS: 'openai_agents',
  MS_AGENT_FRAMEWORK: 'ms_agent_framework',
} as const;

export const LLMAttributes = {
  MODEL_PROVIDER: 'gen_ai.system',
  MODEL_NAME: 'gen_ai.request.model',
  MODEL_VERSION: 'gen_ai.model.version',
  PROMPT: 'gen_ai.prompt',
  COMPLETION: 'gen_ai.completion',
  TOKENS_INPUT: 'gen_ai.usage.input_tokens',
  TOKENS_OUTPUT: 'gen_ai.usage.output_tokens',
  TOKENS_TOTAL: 'gen_ai.usage.total_tokens',
  TEMPERATURE: 'gen_ai.request.temperature',
  MAX_TOKENS: 'gen_ai.request.max_tokens',
  STOP_REASON: 'gen_ai.response.finish_reason',
  LATENCY_MS: 'gen_ai.latency_ms',
} as const;

export const ErrorAttributes = {
  SOURCE: 'error.source',
  CAUSE: 'error.cause',
  SEVERITY: 'error.severity',
  RECOVERY_ACTION: 'error.recovery.action',
  ORIGINAL_ERROR: 'error.original',
} as const;

const frameworkAliases: Record<string, string> = {
  'langchain graph': Frameworks.LANGGRAPH,
  'lang graph': Frameworks.LANGGRAPH,
  langgraph: Frameworks.LANGGRAPH,
  autogen: Frameworks.AUTOGEN,
  'auto gen': Frameworks.AUTOGEN,
  crewai: Frameworks.CREWAI,
  'crew ai': Frameworks.CREWAI,
  'openai agents': Frameworks.OPENAI_AGENTS,
  'openai agents sdk': Frameworks.OPENAI_AGENTS,
  openai_agents: Frameworks.OPENAI_AGENTS,
  'microsoft agent framework': Frameworks.MS_AGENT_FRAMEWORK,
  'ms agent framework': Frameworks.MS_AGENT_FRAMEWORK,
  ms_agent_framework: Frameworks.MS_AGENT_FRAMEWORK,
};

export function normalizeFrameworkName(name: string | null | undefined): string {
  if (!name) return Frameworks.CUSTOM;
  const normalized = name.trim().toLowerCase().replace(/[-_]/g, ' ').replace(/\s+/g, ' ');
  return frameworkAliases[normalized] ?? normalized.replace(/\s+/g, '_');
}