export const AgentAttributes = {
  ID: 'agent.id',
  NAME: 'agent.name',
  ROLE: 'agent.role',
  TEAM: 'agent.team',
  FRAMEWORK: 'agent.framework',
  GOAL: 'agent.goal',
  TASK: 'agent.task',
  TASK_DESCRIPTION: 'agent.task.description',
  CONFIDENCE: 'agent.confidence',
  STATUS: 'agent.status',
  ITERATION: 'agent.iteration',
  DELEGATION_TARGET: 'agent.delegation.target',
  DELEGATION_REASON: 'agent.delegation.reason',
  CRITIQUE_TARGET: 'agent.critique.target',
  CRITIQUE_RESULT: 'agent.critique.result',
  REVIEW_TARGET: 'agent.review.target',
  REVIEW_RESULT: 'agent.review.result',
  HANDOFF_TARGET: 'agent.handoff.target',
  HANDOFF_REASON: 'agent.handoff.reason',
  ESCALATION_TARGET: 'agent.escalation.target',
  ESCALATION_REASON: 'agent.escalation.reason',
  MEMORY_KEY: 'agent.memory.key',
  MEMORY_OPERATION: 'agent.memory.operation',
  TOOL_NAME: 'agent.tool.name',
  TOOL_INPUT: 'agent.tool.input',
  TOOL_OUTPUT: 'agent.tool.output',
  TOOL_STATUS: 'agent.tool.status',
  INTERRUPT_ID: 'agent.interrupt.id',
  INTERRUPT_REASON: 'agent.interrupt.reason',
  INTERRUPT_RESUME_URL: 'agent.interrupt.resume_url',
  RESUME_TOKEN: 'agent.resume.token',
  HUMAN_DECISION: 'agent.human.decision',
  HUMAN_INPUT: 'agent.human.input',
  TIMEOUT_AT: 'agent.timeout_at',
  POLICY_REQUIRED_REVIEW: 'agent.policy.required_review',
} as const;

export const MissionAttributes = {
  ID: 'mission.id',
  OBJECTIVE: 'mission.objective',
  PHASE: 'mission.phase',
  STATUS: 'mission.status',
  OWNER: 'mission.owner',
  TEAM_SIZE: 'mission.team_size',
  ENCRYPTION_ENABLED: 'mission.encryption.enabled',
  FRAMEWORK: 'mission.framework',
  VERSION: 'mission.version',
} as const;

export const AgentEvents = {
  DELEGATION: 'agent.delegation',
  DELEGATION_ACCEPTED: 'agent.delegation.accepted',
  DELEGATION_REJECTED: 'agent.delegation.rejected',
  HANDOFF: 'agent.handoff',
  HANDOFF_REQUESTED: 'agent.handoff.requested',
  HANDOFF_ACCEPTED: 'agent.handoff.accepted',
  HANDOFF_REJECTED: 'agent.handoff.rejected',
  CRITIQUE: 'agent.critique',
  REVIEW: 'agent.review',
  REVIEW_APPROVED: 'agent.review.approved',
  REVIEW_CHANGES_REQUESTED: 'agent.review.changes_requested',
  REVIEW_REJECTED: 'agent.review.rejected',
  REFLECTION: 'agent.reflection',
  PLANNING: 'agent.planning',
  DECISION: 'agent.decision',
  RETRY: 'agent.retry',
  ESCALATION: 'agent.escalation',
  APPROVAL: 'agent.approval',
  TIMEOUT: 'agent.timeout',
  MEMORY_READ: 'agent.memory.read',
  MEMORY_WRITE: 'agent.memory.write',
  MEMORY_DELETE: 'agent.memory.delete',
  TOOL_CALL: 'agent.tool.call',
  TOOL_RESULT: 'agent.tool.result',
  TOOL_ERROR: 'agent.tool.error',
  ARTIFACT_CREATED: 'agent.artifact.created',
  ARTIFACT_UPDATED: 'agent.artifact.updated',
  INTERRUPT_REQUESTED: 'agent.interrupt.requested',
  INTERRUPT_RESUMED: 'agent.interrupt.resumed',
  HUMAN_DECISION: 'agent.human.decision',
  MISSION_STARTED: 'mission.started',
  MISSION_PHASE_CHANGED: 'mission.phase.changed',
  MISSION_COMPLETED: 'mission.completed',
  MISSION_FAILED: 'mission.failed',
} as const;

export const AgentSpanKind = {
  MISSION: 'mission',
  ORCHESTRATION: 'agent.orchestration',
  AGENT_TASK: 'agent.task',
  TASK: 'agent.task',
  DELEGATION: 'agent.delegation',
  TOOL_CALL: 'agent.tool.call',
  REVIEW: 'agent.review',
  REFLECTION: 'agent.reflection',
  PLANNING: 'agent.planning',
  MEMORY_OP: 'agent.memory.op',
  MEMORY: 'agent.memory.op',
  HUMAN_INPUT: 'agent.human.input',
} as const;

export const Frameworks = {
  CUSTOM: 'custom',
  LANGGRAPH: 'langgraph',
  AUTOGEN: 'autogen',
  CREWAI: 'crewai',
  OPENAI_AGENTS: 'openai_agents',
  MS_AGENT_FRAMEWORK: 'ms_agent_framework',
} as const;

const frameworkAliases: Record<string, string> = {
  'langchain graph': Frameworks.LANGGRAPH,
  'lang graph': Frameworks.LANGGRAPH,
  langgraph: Frameworks.LANGGRAPH,
  autogen: Frameworks.AUTOGEN,
  'auto gen': Frameworks.AUTOGEN,
  crewai: Frameworks.CREWAI,
  'crew ai': Frameworks.CREWAI,
  'openai agents': Frameworks.OPENAI_AGENTS,
  'openai agents sdk': Frameworks.OPENAI_AGENTS,
  openai_agents: Frameworks.OPENAI_AGENTS,
  'microsoft agent framework': Frameworks.MS_AGENT_FRAMEWORK,
  'ms agent framework': Frameworks.MS_AGENT_FRAMEWORK,
  ms_agent_framework: Frameworks.MS_AGENT_FRAMEWORK,
};

export function normalizeFrameworkName(name: string | null | undefined): string {
  if (!name) return Frameworks.CUSTOM;
  const normalized = name.trim().toLowerCase().replace(/[-_]/g, ' ').replace(/\s+/g, ' ');
  return frameworkAliases[normalized] ?? normalized.replace(/\s+/g, '_');
}